### ISSUE TITLE
TypeError: Cannot read property 'exp' of undefined

### ISSUE THREAD

**Issue by webcane** [istvan-ujjmeszaros/bootstrap-duallistbox#102]
angular.min.js:117 TypeError: Cannot read property 'exp' of undefined
    at watchFnToHumanReadableString (<anonymous>:703:19)
    at n.$delegate.__proto__.$watch (<anonymous>:735:28)
    at m (http://localhost:8090/mywebapp/resources/plugins/angular/angular-bootstrap-duallistbox.min.js:9:1833)
    at link (http://localhost:8090/mywebapp/resources/plugins/angular/angular-bootstrap-duallistbox.min.js:9:3051)
    at ja (http://localhost:8090/mywebapp/resources/plugins/angular/angular.min.js:80:350)
    at n (http://localhost:8090/mywebapp/resources/plugins/angular/angular.min.js:66:28)
    at g (http://localhost:8090/mywebapp/resources/plugins/angular/angular.min.js:58:305)
    at g (http://localhost:8090/mywebapp/resources/plugins/angular/angular.min.js:58:322)
    at n (http://localhost:8090/mywebapp/resources/plugins/angular/angular.min.js:65:473)
    at g (http://localhost:8090/mywebapp/resources/plugins/angular/angular.min.js:58:305) <select size="25" multiple="multiple" ng-model="roles.selectedRole" ng-options="role.text for role in roles.availableRoles track by role.id" bs-duallistbox="" filter-clear="Очистить фильтр" filter-placeholder="Фильтр" move-selected-label="Перенести выбранную роль" move-all-label="Перенести все роли" remove-selected-label="Убрать выбранную роль" remove-all-label="Убрать все роли" selected-list-label="Выбранные роли" non-selected-list-label="Все роли" info-all="Показаны все {0}" info-empty="Пустой список" info-filtered="<span class=&quot;label label-warning&quot;> at http://localhost:8090/mywebapp/resources/plugins/angular/angular.min.js:89:505

**Comment by istvan-ujjmeszaros** [comment]
Please ping @frapontillo at https://github.com/frapontillo/angular-bootstrap-duallistbox

**Comment by frapontillo** [comment]
With a demo on plunker please, using non minified versions of everything.
